### ISSUE TITLE
nova_plugin fails on openstack-kilo

### ISSUE THREAD

**Issue by mwaldmueller** [rochaporto/collectd-openstack#16]
My setup:
OpenStack Compute (Nova): 2015.1
OS: CentOS 7.1
collectd: 5.5.0

Log message:

<pre>Aug 27 11:01:06 controller collectd[6660]: openstack-nova: failed to get stats :: 'NovaPlugin' object has no attribute 'AllocationRatioCores' :: Traceback (most recent call last):
  File "/usr/lib64/collectd/plugins/openstack/base.py", line 138, in read_callback
    stats = self.get_stats()
  File "/usr/lib64/collectd/plugins/openstack/nova_plugin.py", line 79, in get_stats
    data[self.prefix]['cluster']['config'][item] = getattr(self, item)
AttributeError: 'NovaPlugin' object has no attribute 'AllocationRatioCores'
Aug 27 11:01:06 controller collectd[6660]: Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment
Aug 27 11:01:06 controller collectd[6660]: read-function of plugin `python.nova_plugin' failed. Will suspend it for 120.000 seconds.</pre>

Thanks in advance for your help!

**Comment by knoxadam** [comment]
System:
OpenStack Compute (Nova)
OS: RHEL 7.1
Collectd: 5.5.0.2

Log Message:
collectd.service - Collectd statistics daemon
   Loaded: loaded (/usr/lib/systemd/system/collectd.service; disabled)
   Active: active (running) since Mon 2015-10-12 15:05:56 EDT; 6s ago
     Docs: man:collectd(1)
           man:collectd.conf(5)
 Main PID: 39554 (collectd)
   CGroup: /system.slice/collectd.service
           └─39554 /usr/sbin/collectd -C /etc/collectd.conf -f

Oct 12 15:05:56 asm-os-comp-01-001.osp.epnet.com systemd[1]: Started Collectd statistics daemon.
Oct 12 15:05:56 asm-os-comp-01-001.osp.epnet.com collectd[39554]: Initialization complete, entering read-loop.
Oct 12 15:05:57 asm-os-comp-01-001.osp.epnet.com collectd[39554]: openstack-nova: failed to get stats :: 'NovaPlugin' object has no attribute 'AllocationRatioCores' :: Traceback (most recent call last):
                                                                    File "/var/lib/collectd/base.py", line 149, in read_callback
                                                                      stats = self.get_stats()
                                                                    File "/var/lib/collectd/nova_plugin.py", line 85, in get_stats
                                                                      data[self.prefix]['cluster']['config'][item] = getattr(self, item)
                                                                  AttributeError: 'NovaPlugin' object has no attribute 'AllocationRatioCores'
Oct 12 15:05:57 asm-os-comp-01-001.osp.epnet.com collectd[39554]: Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment
Oct 12 15:05:57 asm-os-comp-01-001.osp.epnet.com collectd[39554]: read-function of plugin `python.nova_plugin' failed. Will suspend it for 120.000 seconds.

**Comment by santhoshpadala** [comment]
Hi,
Kilo Version
Openstack glance 
OpenStack Compute (Nova)
Openstack  Cinder
OpenstacK Neutron

OS :UBUNTU 14.4
Collectd: 

Iam trying to see openstack logs in Graphite dashboard . Iam able to see Keystone Plugins using your github document. But iam unable to see remaining services. Its showing plugin failed. Please try to send me or share me Remaining Plugin config files.
Error:
[2016-12-02 12:17:01] Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment
[2016-12-02 12:17:01] read-function of plugin `python.glance_plugin' failed. Will suspend it for 120.000 seconds.
